movies/urls.py
from django.urls import path, include
from movies import views

app_name = "movies"

urlpatterns = [
    path("", views.index, name="index"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("add", views.add, name="add"),
    path("select/<str:title>", views.select, name="select"),
    path("delete/<int:id>", views.delete, name="delete"),
    path("find/<int:id>", views.find, name="find"),
]

portfolio/urls.py
from django.urls import path, include
from portfolio import views

app_name = "portfolio"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("thanks", views.thanks, name="thanks"),
    path("twitter-about", views.twitter_about, name="twitter_about"),
    path("zscraper-about", views.zillow_about, name="zillow_about"),
    path("stocks-about", views.stocks_about, name="stocks_about"),
    path("movies-about", views.movies_about, name="movies_about"),
    path("blog-about", views.blog_about, name="blog_about"),
    path("auctions-about", views.auctions_about, name="auctions_about"),
    path("anf-about", views.anf_about, name="anf_about"),
]

twitter/urls.py
from django.urls import path
from twitter import views

app_name = "twitter"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<int:pk>", views.user_profile, name="user_profile"),
    path("follow/<int:id>", views.follow, name="follow"),
    path("unfollow/<int:id>", views.unfollow, name="unfollow"),
    path("send-tweet/<int:pk>", views.send_tweet, name="send_tweet"),
    path("following/<int:pk>", views.user_following, name="user_following"),
    # API
    path("like", views.like, name="like"),
    path("get-tweet/<int:id>", views.get_tweet, name="get_tweet"),
    path("edit-tweet", views.edit_tweet, name="edit_tweet"),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from portfolio import urls as portfolio_urls
from movies import urls as movies_urls
from twitter import urls as twitter_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(portfolio_urls)),
    path("movies/", include(movies_urls)),
    path("twitter/", include(twitter_urls)),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms
from django.core.exceptions import ValidationError
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class HoneypotField(forms.BooleanField):
    default_widget = forms.CheckboxInput({
        "style": "display:none !important;",
        "tabindex": "-1",
        "autocomplete": "off"
    })

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", HoneypotField.default_widget)
        kwargs["required"] = False
        super().__init__(*args, **kwargs)

    def clean(self, value):
        if cleaned_value := super().clean(value):
            raise ValidationError("")
        else:
            return cleaned_value


class ContactForm(forms.Form):
    your_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"}),
        label="Your Name",
        max_length=100,
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"class": "form-control py-4"}),
        label="Your email address",
        max_length=150,
    )
    message = forms.CharField(widget=forms.Textarea(
        attrs={"class": "form-control py-3"}))
    ghtd = HoneypotField()
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

portfolio/views.py
# pylint: disable=E1101
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ContactForm
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import From, To, Mail
import os
from dotenv import load_dotenv

load_dotenv()


def index(request):
    return render(request, "portfolio/index.html")


def twitter_about(request):
    return render(request, "portfolio/twitter-about.html")


def zillow_about(request):
    return render(request, "portfolio/zscraper-about.html")


def stocks_about(request):
    return render(request, "portfolio/stocks-about.html")


def movies_about(request):
    return render(request, "portfolio/movies-about.html")


def blog_about(request):
    return render(request, "portfolio/blog-about.html")


def auctions_about(request):
    return render(request, "portfolio/auctions-about.html")


def anf_about(request):
    return render(request, "portfolio/anf-about.html")


def thanks(request):
    return render(request, "portfolio/thanks.html")


def contact(request):
    if request.POST:
        form = ContactForm(request.POST)

        # Validate the form: the captcha field will automatically
        # check the input
        if form.is_valid():
            subject = "Contact Form"
            name = form.cleaned_data["your_name"]
            message = form.cleaned_data["message"]
            sender = form.cleaned_data["email"]
            human = True

            message = Mail(
                from_email=From(os.environ["SG_RECEIVER_EMAIL"], name),
                to_emails=To(os.environ["SG_RECEIVER_EMAIL"], "Marceia"),
                subject="Contact Form",
                html_content=
                f"Name: {name} from Email: {sender}<br /> Message: {message}",
            )
            try:
                sg = SendGridAPIClient(os.environ.get("SENDGRID_API_KEY"))
                response = sg.send(message)
                print(response.status_code)
                print(response.body)
                print(response.headers)
            except Exception as e:
                print(e.to_dict)
            return redirect("portfolio:thanks")
    else:
        form = ContactForm()

    return render(request, "portfolio/contact.html", {"form": form})

portfolio/templates/portfolio/contact.html
{% extends "portfolio/layout.html" %}
{% block title %}
  Contact Me
{% endblock %}

{% block body %}

  <section>
    <div class="container mt-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-8 text-center">
          <h2>What to chat?</h2>
          <p class="lead mb-0">Contact me and let's discuss next steps!</p>
          <p class="mb-5">My LinkedIn and Resume (See 'About Me' in top menu) also contain my direct contact info.</p>
        </div>
      </div>

      <div class="row pb-5 row justify-content-center">
        <form class="col-md-6" method="post">
          {% csrf_token %}
          <div class="row gx-5 mb-4">
            <div class="col-md-6">
              <label class="text-dark mb-2" for="{{ form.your_name.id_for_label }}">Full name</label>
              {{ form.your_name }}
            </div>
            <div class="col-md-6">
              <label class="text-dark mb-2" for="{{ form.email.id_for_label }}">Email</label>
              {{ form.email }}
            </div>
          </div>
          <div class="mb-4">
            <label class="text-dark mb-2" for="{{ form.message.id_for_label }}">Message</label>
            {{ form.message }}
          </div>
          <div>{{ form.ghtd }}</div>
          <div>{{ form.captcha }}</div>
          <div class="text-center">
            <button class="btn btn-primary mt-4" type="submit">Submit Request</button>
          </div>
        </form>
      </div>
    </div>
    <div class="svg-border-rounded text-dark">
      <!-- Rounded SVG Border-->
      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 144.54 17.34" preserveaspectratio="none" fill="currentColor">
        <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
      </svg>
    </div>
  </div>
</section>
{% endblock body %}

portfolio/templates/portfolio/index.html
{% extends "portfolio/layout.html" %}
{% block title %}
  Marceia Egler - Python Software Developer
{% endblock %}

{% block body %}
  <!-- Page Header-->
  <header class="page-header-ui page-header-ui-light bg-white">
    <div class="page-header-ui-content">
      <div class="container px-5">
        <div class="row gx-5 justify-content-center">
          <div class="col-xl-8 col-lg-10 text-center">
            <div class="headshot--landscape"><img src="./static/portfolio/images/headshot2022.png"/></div>

            <h1 class="page-header-ui-title">Marceia Egler - Python Developer</h1>
            <p class="page-header-ui-text">I am a Python developer based in Orlando, Florida. I help convert ideas into meaningful and useful products. With a sharp eye for product evolution, I prioritize tasks, iterate and deliver.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="svg-border-rounded text-light">
      <!-- Rounded SVG Border-->
      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 144.54 17.34" preserveaspectratio="none" fill="currentColor">
        <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
      </svg>
    </div>
  </header>
  <!-- Icon Section-->
  <section class="bg-light py-10">
    <div class="container px-5">
      <div class="row gx-5 text-center">
        <div class="col-lg-4 mb-5 mb-lg-0">
          <img class="icon-svg-middle" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original-wordmark.svg"/>

        </div>
        <div class="col-lg-4 mb-5 mb-lg-0 text-start">
          <p>
            Organizations are increasingly using the Python programming language to realize a host of objectives.
          </p>
          <p>
            Companies today are using the language in multiple ways to execute a vast range of front and back-end processes across web development, machine learning, and various other disciplines.
          </p>
          <p>
            With the ability to integrate Javascript for front-end interactivity, along with frameworks such as Django, Flask and others, the possibilities are endless.
          </p>
        </div>
        <div class="col-lg-4">
          <img class="icon-svg-middle" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"/>

        </div>
      </div>
    </div>
    <div class="svg-border-rounded text-white">
      <!-- Rounded SVG Border-->
      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 144.54 17.34" preserveaspectratio="none" fill="currentColor">
        <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
      </svg>
    </div>
  </section>
  <!-- Content Section-->
  <section class="bg-white py-10">
    <div class="container px-5">
      <div class="row gx-5">
        <div class="col-md-6 col-xl-4 mb-5 mt-n5">
          <h2>Featured Projects</h2>
        </div>
      </div>
      <div class="row gx-5">
        {# Photo by Noelle Otto from Pexels: https://www.pexels.com/photo/close-up-photography-of-magnifying-glass-906055/ #}
        <div class="col-md-12 col-lg-12 col-xl-4 mb-5 mt-xl-n5">
          <a class="card card-portfolio h-100" href="{% url 'portfolio:anf_about' %}">
            <img class="card-img-top" src="./static/portfolio/images/pexels-noelle-otto-906055.jpg" alt="..."/>

            <h3 class="text-center">Amazon Niche Finder - An Affiliate Marketing Research Tool</h3>
          </a>
        </div>

        <div class="col-md-12 col-lg-12 col-xl-4 mb-5 mt-md-n5">
          <a class="card card-portfolio h-100" href="{% url 'portfolio:twitter_about' %}">
            {# Photo by Skyler Ewing: https://www.pexels.com/photo/eastern-bluebird-with-bright-plumage-on-stick-6719830/ #}
            <img class="card-img-top" src="./static/portfolio/images/pexels-skyler-ewing-6719830.jpg" alt="..."/>

            <h3 class="text-center">Twitter Clone - Django/JS SPA App</h3>
          </a>
        </div>
        {# Photo by RODNAE Productions: https://www.pexels.com/photo/wooden-sticks-on-white-wooden-table-7978779/ #}
        <div class="col-md-12 col-lg-12 col-xl-4 mb-5 mt-n5">
          <a class="card card-portfolio h-100" href="{% url 'portfolio:auctions_about' %}">
            <img class="card-img-top" src="./static/portfolio/images/pexels-rodnae-productions-7978779.jpg" alt="..."/>

            <h3 class="text-center">Accio Auctions - An Ecommerce Demo</h3>
          </a>
        </div>
      </div>
      <div class="row gx-5 d-flex justify-content-center mt-3">
        {# Photo by Jessica Lewis Creative: https://www.pexels.com/photo/photo-of-phone-on-top-of-notebook-3361492/ #}
        <div class="col-md-12 col-lg-12 col-xl-4 mb-5 mt-xl-n5">
          <a class="card card-portfolio h-100" href="{% url 'portfolio:blog_about' %}">
            <img class="card-img-top" src="./static/portfolio/images/pexels-jessica-lewis-creative-3361492.jpg" alt="..."/>

            <h3 class="text-center">change_blog - A Personal Blog Built With Flask</h3>
          </a>
        </div>
      </div>
    </div>

    <div class="svg-border-rounded text-light">
      <!-- Rounded SVG Border-->
      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 144.54 17.34" preserveaspectratio="none" fill="currentColor">
        <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
      </svg>
    </div>
  </section>
  <!-- Icon Section-->

  <section class="bg-light py-10">
    <div class="container px-5">
      <div class="row gx-5 text-center">
        <div class="col-lg-4 mb-5 mb-lg-0">
          <div class="devicon-stack mb-4">
            <img class="icon-svg px-1" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original-wordmark.svg"/>
            <img class="icon-svg px-1" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original-wordmark.svg"/>
          </div>
          <h3>Databases</h3>
          <p class="mb-0">My knowledge with these modern databases ensure I can develop your application with most commonly used full stacks that are Python and/or Javascript based.</p>
        </div>
        <div class="col-lg-4  mb-lg-0">
          <div class="devicon-stack mb-4">
            <img class="icon-svg px-1" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain-wordmark.svg"/>
            <img class="icon-svg px-1" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original-wordmark.svg"/>
          </div>
          <h3>Frameworks</h3>
          <p class="mb-0">Whether you want a "batteries included" solution like Django or an "à la carte" alternative such as Flask, I can build the app and make it a reality.</p>
        </div>
        <div class="col-lg-4 mb-5">
          <div class="devicon-stack mb-4">
            <img class="icon-svg px-1" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original-wordmark.svg"/>
            <img class="icon-svg px-1" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original-wordmark.svg"/>
          </div>
          <h3>Version Control</h3>
          <p class="mb-0">As development environments have accelerated, version control systems help software teams work faster and smarter. By embracing version control, you can be confident my work is tested, saved and commited.</p>
        </div>
      </div>
    </div>
    <div class="svg-border-rounded text-white">
      <!-- Rounded SVG Border-->
      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 144.54 17.34" preserveaspectratio="none" fill="currentColor">
        <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
      </svg>
    </div>
  </section>
  <!-- Content Section-->
  <section class="bg-white py-10">
    <div class="container px-5">
      <div class="row gx-5">
        <div class="col-md-6 col-xl-4 mb-5 mt-n5">
          <h2>Small Projects and Code Challenges</h2>
        </div>
      </div>
      <div class="row gx-5">
        <div class="col-md-6 col-xl-4 mb-5 mt-n5">
          <a class="card card-portfolio h-100" href="{% url 'portfolio:movies_about' %}">
            <img class="card-img-top" src="./static/portfolio/images/pexels-pixabay-33129.jpg" alt="..."/>
            <div class="card-body">
              <div class="card-title">Movie Picker</div>
            </div>
            <h3 class="text-center">Movie Picker</h3>
          </a>
        </div>
        {# Photo by Liza Summer: https://www.pexels.com/photo/crop-dealer-touching-screen-on-smartphone-with-trading-application-6347705/ #}
        <div class="col-md-6 col-xl-4 mb-5 mt-md-n5">
          <a class="card card-portfolio h-100" href="{% url 'portfolio:stocks_about' %}">
            <img class="card-img-top" id="small-project2" src="./static/portfolio/images/pexels-liza-summer-6347705.jpg" alt="..."/>
            <div class="card-body">
              <div class="card-title">Stock News Alerts</div>
            </div>
            <h3 class="text-center">Stock News Alerts</h3>
          </a>
        </div>
        {# Photo by Jessica Bryant: https://www.pexels.com/photo/assorted-color-wall-paint-house-photo-1370704/#}
        <div class="col-md-6 col-xl-4 mb-5 mt-xl-n5">
          <a class="card card-portfolio h-100" href="{% url 'portfolio:zillow_about' %}">
            <img class="card-img-top" id="small-project3" src="./static/portfolio/images/pexels-jessica-bryant-1370704.jpg" alt="..."/>
            <div class="card-body">
              <div class="card-title">Zillow Scraper</div>
            </div>
            <h3 class="text-center">Zillow Scraper</h3>
          </a>
        </div>
      </div>
    </div>
    <div class="svg-border-rounded text-light">
      <!-- Rounded SVG Border-->
      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 144.54 17.34" preserveaspectratio="none" fill="currentColor">
        <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
      </svg>
    </div>
  </section>
  <!--Contact Section-->
  <section class="bg-light py-10">
    <div class="container px-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-8 text-center">
          <h2>Contact me</h2>
          <div class="row gx-5">
            <div class="col">
              <a class="text-decoration-none" href="{% url 'portfolio:contact' %}">
                <div class="card">
                  <div class="card-body">
                    <div class="icon-stack icon-stack-lg bg-orange text-white mb-3">
                      <i class="fa-lg fa-regular fa-envelope"></i>
                    </div>
                    <div class="small">
                      Email
                    </div>
                  </div>
                </div>
              </a>
            </div>
            <div class="col">
              <a class="text-decoration-none" href="https://www.linkedin.com/in/marceia-egler" target="_blank" rel="noopener noreferrer">
                <div class="card">
                  <div class="card-body">
                    <div class="icon-stack icon-stack-lg bg-blue text-white mb-3">
                      <i class="fa-lg fa-brands fa-linkedin"></i>
                    </div>
                    <div class="small">
                      LinkedIn
                    </div>
                  </div>
                </div>
              </a>
            </div>
            <div class="col">
              <a class="text-decoration-none" href="https://github.com/megler" target="_blank" rel="noopener noreferrer">
                <div class="card">
                  <div class="card-body">
                    <div class="icon-stack icon-stack-lg bg-green text-white mb-3">
                      <i class="fa-lg fa-brands fa-github"></i>
                    </div>
                    <div class="small">
                      GitHub
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="svg-border-rounded text-dark">
      <!-- Rounded SVG Border-->
      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 144.54 17.34" preserveaspectratio="none" fill="currentColor">
        <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
      </svg>
    </div>
  </section>
</main>
</div>
{% endblock %}

portfolio/templates/portfolio/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.14.0/devicon.min.css">
    <link href="{% static 'portfolio/styles/styles.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'portfolio/images/favicon.ico' %}"/>
    <script src="https://kit.fontawesome.com/347d408513.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.24.1/feather.min.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id="layoutDefault">
      <div id="layoutDefault_content">
        <main>
          <!-- Navbar-->
          <nav class="navbar navbar-marketing navbar-expand-lg bg-light navbar-light">
            <div class="container px-5">
              <div class="icon-stack icon-stack-sm bg-green text-white mb-3 mx-1">
                <a class="icon-links" href="https://github.com/megler" target="_blank" rel="noopener noreferrer">
                  <i class="fa-sm fa-brands fa-github"></i>
                </a>

              </div>
              <div class="icon-stack icon-stack-sm bg-blue text-white mb-3 mx-1">
                <a class="icon-links" href="https://www.linkedin.com/in/marceia-egler" target="_blank" rel="noopener noreferrer">
                  <i class="fa-sm fa-brands fa-linkedin"></i>
                </a>
              </div>

              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i data-feather="menu"></i>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto me-lg-5">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:index' %}">Home</a>
                  </li>
                  <li class="nav-item dropdown dropdown-lg no-caret">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownPages" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Projects
                      <i class="fas fa-chevron-right dropdown-arrow"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end me-lg-n20 me-xl-n15 animated--fade-in-up" aria-labelledby="navbarDropdownPages">
                      <div class="row g-0 justify-content-center">
                        <div class="col-lg-4 p-lg-6">
                          <h6 class="dropdown-header text-primary">Featured</h6>
                          <a class="dropdown-item" href="{% url 'portfolio:anf_about' %}">Amazon Niche Finder - SaaS</a>
                          <a class="dropdown-item" href="{% url 'portfolio:twitter_about' %}">Twitter Clone</a>
                          <a class="dropdown-item" href="{% url 'portfolio:auctions_about' %}">Accio Auctions Ecommerce</a>
                          <a class="dropdown-item" href="{% url 'portfolio:blog_about' %}">change_blog Flask Demo</a>
                          <div class="dropdown-divider border-0"></div>
                        </div>
                        <div class="col-lg-3"></div>
                        <div class="col-lg-4 p-lg-6">
                          <h6 class="dropdown-header text-primary">Small Projects</h6>
                          <a class="dropdown-item" href="{% url 'portfolio:movies_about' %}">Movie Picker</a>
                          <a class="dropdown-item" href="{% url 'portfolio:stocks_about' %}">Stock News Alerts</a>
                          <a class="dropdown-item" href="{% url 'portfolio:zillow_about' %}">Zillow Scraper</a>
                          <div class="dropdown-divider border-0 d-lg-none"></div>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="nav-item dropdown no-caret">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownDocs" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      About Me
                      <i class="fas fa-chevron-right dropdown-arrow"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end animated--fade-in-up" aria-labelledby="navbarDropdownDocs">

                      <a class="dropdown-item py-3" href="https://www.linkedin.com/in/marceia-egler" target="_blank" rel="noopener noreferrer">
                        <div class="icon-stack bg-primary-soft text-primary me-4">
                          <i data-feather="file-text"></i>
                        </div>
                        <div>
                          <div class="small text-gray-500">Documentation</div>
                          LinkedIn
                        </div>
                      </a>
                      <div class="dropdown-divider m-0"></div>
                      <a class="dropdown-item py-3" href="https://github.com/megler/" target="_blank" rel="noopener noreferrer">
                        <div class="icon-stack bg-primary-soft text-primary me-4">
                          <i data-feather="code"></i>
                        </div>
                        <div>
                          <div class="small text-gray-500">Code</div>
                          Github Repositories
                        </div>
                      </a>
                      <div class="dropdown-divider m-0"></div>
                      <a class="dropdown-item py-3" href="https://www.changeblog.info/" target="_blank" rel="noopener noreferrer">
                        <div class="icon-stack bg-primary-soft text-primary me-4">
                          <i data-feather="book-open"></i>
                        </div>
                        <div>
                          <div class="small text-gray-500">Blog</div>
                          Personal Blog
                        </div>
                      </a>
                    </div>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href='{% url "portfolio:contact" %}'>Contact Me</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          {% block body %}{% endblock %}
          <div id="layoutDefault_footer">
            <footer class="footer pt-10 pb-5 mt-auto bg-dark footer-dark">
              <div class="container px-5">

                <div class="row gx-5 align-items-center">
                  <div class="col small text-center">Copyright &copy; Marceia.me 2022</div>
                </div>
              </div>
            </footer>
          </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'portfolio/js/scripts.js' %}"></script>
      </body>

    </html>

portfolio/templates/portfolio/thanks.html
{% extends "portfolio/layout.html" %}
{% block title %}
  Thanks!
{% endblock %}

{% block body %}

  <div class="container mt-5">
    <div class="jumbotron text-center">
      <h1 class="display-4">Thanks!</h1>
      <p class="lead">I'll get back to you within 24 hours!</p>
    </div>
  </div>

{% endblock body %}