movies/urls.py
from django.urls import path, include
from movies import views

app_name = "movies"

urlpatterns = [
    path("", views.index, name="index"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("add", views.add, name="add"),
    path("select/<str:title>", views.select, name="select"),
    path("delete/<int:id>", views.delete, name="delete"),
    path("find/<int:id>", views.find, name="find"),
]

portfolio/urls.py
from django.urls import path, include
from portfolio import views

app_name = "portfolio"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("thanks", views.thanks, name="thanks"),
    path("twitter-about", views.twitter_about, name="twitter_about"),
    path("zscraper-about", views.zillow_about, name="zillow_about"),
    path("stocks-about", views.stocks_about, name="stocks_about"),
    path("movies-about", views.movies_about, name="movies_about"),
    path("blog-about", views.blog_about, name="blog_about"),
    path("auctions-about", views.auctions_about, name="auctions_about"),
    path("anf-about", views.anf_about, name="anf_about"),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from portfolio import urls as portfolio_urls
from movies import urls as movies_urls
from twitter import urls as twitter_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(portfolio_urls)),
    path("movies/", include(movies_urls)),
    path("twitter/", include(twitter_urls)),
]

movies/models.py
from django.db import models


class Movie(models.Model):
    title = models.CharField(max_length=255, unique=True, blank=False)
    year = models.IntegerField(blank=False)
    description = models.TextField(blank=False)
    rating = models.FloatField(blank=False, null=True)
    ranking = models.IntegerField(blank=False, null=True)
    review = models.TextField(blank=False, null=True)
    img_url = models.URLField(
        blank=False,
        unique=True,
    )

movies/forms.py
from django import forms


class Movie_Title(forms.Form):
    movie_title = forms.CharField(
        required=True, widget=forms.TextInput(attrs={"class": "form-control"}))


class Movie_Rating(forms.Form):
    movie_rating = forms.FloatField(widget=forms.NumberInput(
        attrs={
            "class": "form-control",
            "min": 0,
            "max": 10,
            "type": "number"
        }))
    movie_review = forms.CharField(widget=forms.Textarea(
        attrs={"class": "form-control"}))

movies/views.py
from json import load
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from dotenv import load_dotenv
from movies.models import Movie
from movies.forms import Movie_Title, Movie_Rating
import os, requests, json

load_dotenv()

MDB_API_KEY = os.environ.get("MDB_API_KEY")


def index(request):

    all_movies = Movie.objects.filter().order_by("-rating")
    return render(request, "movies/index.html", {"movies": all_movies})


def add(request):
    if request.POST:
        add_movie_form = Movie_Title(request.POST)
        if add_movie_form.is_valid():
            movie_title = add_movie_form.cleaned_data["movie_title"]
            return HttpResponseRedirect(
                reverse("movies:select", kwargs={"title": movie_title}))
    else:
        add_movie_form = Movie_Title()

    return render(request, "movies/add.html", {"form": add_movie_form})


def edit(request, id):
    movie_to_update = Movie.objects.get(pk=id)
    if request.POST:
        update_form = Movie_Rating(request.POST)
        if update_form.is_valid():
            movie_rating = update_form.cleaned_data["movie_rating"]
            movie_review = update_form.cleaned_data["movie_review"]
            movie_to_update.rating = movie_rating
            movie_to_update.review = movie_review
            movie_to_update.save()
            return HttpResponseRedirect(reverse("movies:index"))
    else:
        update_form = Movie_Rating()

    return render(
        request,
        "movies/edit.html",
        {
            "form": update_form,
            "id": id,
            "movie": movie_to_update
        },
    )


def delete(request, id):
    movie_to_delete = Movie.objects.get(pk=id)
    movie_to_delete.delete()
    return HttpResponseRedirect(reverse("movies:index"))


def select(request, title):
    params = {"api_key": MDB_API_KEY, "query": title, "language": "en-US"}

    movie_search = requests.get("https://api.themoviedb.org/3/search/movie",
                                params=params)
    movie_search.raise_for_status()
    data = json.loads(movie_search.text)
    return render(request, "movies/select.html", {"movies": data})


def find(request, id):
    movie_id = id
    params = {"api_key": MDB_API_KEY, "language": "en-US"}
    movie_title_search = requests.get(
        f"https://api.themoviedb.org/3/movie/{movie_id}", params=params)
    movie_title_search.raise_for_status()
    data = json.loads(movie_title_search.text)
    img_id = data["poster_path"]
    add_movie_db = Movie(
        title=data["title"],
        year=data["release_date"][0:4],
        description=data["overview"],
        img_url=f"https://image.tmdb.org/t/p/w500/{img_id}",
    )
    add_movie_db.save()

    return HttpResponseRedirect(reverse("movies:index"))

movies/templates/movies/add.html
{% extends "movies/base.html" %}

{% block title %}Add Movie{% endblock %}

{% block body %}
  <div class="container mt-5">
    <div class="content">
      <h1 class="heading">Add a Movie</h1>
      <form method="post">
        {% csrf_token %}
        <div class="row mb-3">
          <label for="id_movie_title" class="form-label">Movie Title</label>
          {{ form.movie_title }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}

movies/templates/movies/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'movies/images/favicon.ico' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'movies/styles.css' %}">

    <title>
      {% block title %}{% endblock title %}
    </title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="collapse navbar-collapse justify-content-center " id="navbarSupportedContent">
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'movies:index' %}">Movie Project Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'portfolio:index' %}">Return To Portfolio</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block body %}{% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>

</html>

movies/templates/movies/edit.html
{% extends "movies/base.html" %}

{% block title %}Edit Movies{% endblock %}

{% block body %}
  <div class="container mt-5">
    <div class="content">
      <h1 class="heading">{{ movie.title }}
      </h1>
      <p class="description">Edit Movie Rating</p>
      <form method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="id_movie_rating" class="form-label">Your Rating out of 10 (eg. 7.5)</label>
          {{ form.movie_rating }}
        </div>
        <div class="mb-3">
          <label for="id_movie_review" class="form-label">Movie Review</label>
          {{ form.movie_review }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}

movies/templates/movies/index.html
{% extends "movies/base.html" %}

{% block title %}
  My Top 10 Movies
{% endblock %}

{% block body %}
  <div class="container mt-5">
    <h1 class="heading">My Favorite Movies</h1>
    <p class="description">Hover over each movie to see more!</p>
    <div class="container text-center add">
      <a href="{% url 'movies:add' %}" class="button">Add Movie</a>
    </div>
    <div class="row justify-content-center">
      {% for movie in movies %}
        <div class="col-4 ">
          <div class="card">
            <div class="front" style="background-image: url({{ movie.img_url }});">
              <p class="large">{{ forloop.counter }}</p>
            </div>
            <div class="back">
              <div>
                <div class="title">{{ movie.title }}
                  <span class="release_date">{{ movie.year }}</span></div>
                <div class="rating">
                  <label>{{ movie.rating }}</label>
                  <i class="fas fa-star star"></i>
                </div>
                <p class="review">{{ movie.review }}</p>
                <p class="overview">
                  {{ movie.description }}
                </p>
                <a href="{% url 'movies:edit' id=movie.id %}" class="button">Update</a>
                <a href="{% url 'movies:delete' id=movie.id %}" class="button delete-button">Delete</a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

movies/templates/movies/select.html
{% extends "movies/base.html" %}

{% block title %}Select Movie{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="heading">Select Movie</h1>
    {% for movie in movies.results %}
      <p>
        <a href="{% url 'movies:find' id=movie.id %}">
          {{ movie.title }}
          -
          {{ movie.release_date }}
        </a>
      </p>
    {% endfor %}
  </div>
{% endblock %}