movies/urls.py
from django.urls import path, include
from movies import views

app_name = "movies"

urlpatterns = [
    path("", views.index, name="index"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("add", views.add, name="add"),
    path("select/<str:title>", views.select, name="select"),
    path("delete/<int:id>", views.delete, name="delete"),
    path("find/<int:id>", views.find, name="find"),
]

portfolio/urls.py
from django.urls import path, include
from portfolio import views

app_name = "portfolio"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("thanks", views.thanks, name="thanks"),
    path("twitter-about", views.twitter_about, name="twitter_about"),
    path("zscraper-about", views.zillow_about, name="zillow_about"),
    path("stocks-about", views.stocks_about, name="stocks_about"),
    path("movies-about", views.movies_about, name="movies_about"),
    path("blog-about", views.blog_about, name="blog_about"),
    path("auctions-about", views.auctions_about, name="auctions_about"),
    path("anf-about", views.anf_about, name="anf_about"),
]

twitter/urls.py
from django.urls import path
from twitter import views

app_name = "twitter"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<int:pk>", views.user_profile, name="user_profile"),
    path("follow/<int:id>", views.follow, name="follow"),
    path("unfollow/<int:id>", views.unfollow, name="unfollow"),
    path("send-tweet/<int:pk>", views.send_tweet, name="send_tweet"),
    path("following/<int:pk>", views.user_following, name="user_following"),
    # API
    path("like", views.like, name="like"),
    path("get-tweet/<int:id>", views.get_tweet, name="get_tweet"),
    path("edit-tweet", views.edit_tweet, name="edit_tweet"),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from portfolio import urls as portfolio_urls
from movies import urls as movies_urls
from twitter import urls as twitter_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(portfolio_urls)),
    path("movies/", include(movies_urls)),
    path("twitter/", include(twitter_urls)),
]

twitter/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class User(AbstractUser):
    def __str__(self):
        return f"{self.username}"


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    background_image = models.URLField(null=True)
    date_joined = models.DateField(auto_now=False,
                                   auto_now_add=False,
                                   null=False,
                                   default=now)
    followers = models.ManyToManyField(User,
                                       blank=True,
                                       related_name="followed_by")

    def __str__(self):
        return f"{self.user.first_name}"


class Post(models.Model):
    author = models.ForeignKey(User,
                               null=True,
                               on_delete=models.CASCADE,
                               related_name="author")
    post_body = models.CharField(max_length=500000)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post_body[0:5]}"


class Like(models.Model):

    user_liked = models.ForeignKey(User,
                                   null=True,
                                   on_delete=models.CASCADE,
                                   related_name="user")
    post_liked = models.ForeignKey(
        Post,
        null=True,
        on_delete=models.CASCADE,
        related_name="post",
    )

    def __str__(self):
        return f"User {self.user_liked.username} likes {self.post_liked.post_body[0:5]}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

twitter/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.core import serializers
from twitter.util import *
from twitter.models import User, Post, Like, Profile
import json, traceback


def index(request):
    """When visiting homepage, show all tweets"""

    all_tweets = Post.objects.all()
    tweets = sort_tweets(all_tweets)
    tweets = paginate(request, tweets)
    likes = like_count()

    return render(
        request,
        "twitter/index.html",
        {
            "posts": tweets,
            "likes": likes,
        },
    )


def login_view(request):
    """Allow registered user to login"""
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("twitter:index"))
        else:
            return render(
                request,
                "twitter/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "twitter/login.html")


def logout_view(request):
    """Allow registered user to logout"""
    logout(request)
    return HttpResponseRedirect(reverse("twitter:index"))


def register(request):
    """Allow unregistered user to register"""
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        first_name = request.POST["first_name"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "twitter/register.html",
                          {"message": "Passwords must match."})

        # Attempt to create new user
        try:
            user = User.objects.create_user(username,
                                            email,
                                            password,
                                            first_name=first_name)
            user.save()
            # Save userinfo record
            user = User.objects.get(pk=user.id)
            user.profile.background_image = request.POST["background_img"]
            user.save()
        except IntegrityError:
            return render(request, "twitter/register.html",
                          {"message": "Username already taken."})
        login(request, user)
        return HttpResponseRedirect(reverse("twitter:index"))
    else:
        return render(request, "twitter/register.html")


def user_profile(request, pk):
    """Returns a user profile page for a specific user"""
    user_profile_id = User.objects.get(pk=pk)
    specific_tweets = Post.objects.filter(author__id=pk)
    tweets = sort_tweets(specific_tweets)
    tweets = paginate(request, tweets)
    num_tweets = tweet_count(pk)
    likes = like_count()
    is_following = confirm_user_follows(request, pk)

    # get a suggested follower list and limit to 10
    if request.user.is_authenticated:
        other_users = who_to_follow(request)[:10]

    # get followers/following count from util.py
    user_following_count, user_followed_by_count = follow_nums(user_profile_id)

    return render(
        request,
        "twitter/profile.html",
        {
            "likes": likes,
            "tweet_count": num_tweets,
            "is_following": is_following,
            "user_follows": user_following_count,
            "user_followed_by": user_followed_by_count,
            "user_profile_id": user_profile_id,
            "posts": tweets,
            "follow_suggestions": other_users,
        },
    )


@login_required(login_url="login")
def send_tweet(request, pk):
    """Allows an authenticated user to send a tweet"""
    if request.method == "POST":
        user = User.objects.get(pk=request.user.id)
        tweet_body = request.POST["tweet_body"]
        new_tweet = Post.objects.create(author=user, post_body=tweet_body)
        new_tweet.save()
        return user_profile(request, pk)


@login_required(login_url="login")
def edit_tweet(request):
    """Allows an authenticated user to edit their own tweet."""
    data = json.loads(request.body)
    id = data.get("id", "")
    body = data.get("post_body", "")
    edited_tweet = Post.objects.get(pk=int(id))
    edited_tweet.post_body = body
    edited_tweet.save()
    return JsonResponse({"status": 201})


@login_required(login_url="login")
def user_following(request, pk):
    """Returns a list of who the user is following and those user's tweets."""
    followed_people = Profile.objects.filter(followers__id=pk).values("user")
    tweets = Post.objects.filter(author__in=followed_people)
    tweets = sort_tweets(tweets)
    tweets = paginate(request, tweets)
    return render(
        request,
        "twitter/following.html",
        {"posts": tweets},
    )


# Functionality views that didn't belong in utilities.py


def follow(request, id):
    """Functionality to follow a user"""
    if request.method == "POST":
        to_follow = Profile.objects.get(user=id)
        to_follow.followers.add(request.user)
        to_follow.save()
        return user_profile(request, id)


def unfollow(request, id):
    """Functionality to unfollow a user"""
    if request.method == "POST":
        to_unfollow = Profile.objects.get(user=id)
        to_unfollow.followers.remove(request.user)
        to_unfollow.save()
        return user_profile(request, id)


@login_required(login_url="login")
def like(request):
    """Functionality to like a user"""
    # Get form data
    data = json.loads(request.body)
    post_id = data.get("post_liked", "")
    post = Post.objects.get(pk=int(post_id))
    user_who_likes = Like.objects.filter(user_liked=request.user.id,
                                         post_liked=post)
    if request.method == "POST":
        if not user_who_likes:
            try:
                like = Like(user_liked=request.user, post_liked=post)
                like.save()
                return JsonResponse({"message": "Successful"}, status=201)
            except BaseException as error:
                print("An exception occurred: {}".format(error))
        if user_who_likes:
            try:
                Like.objects.filter(user_liked=request.user,
                                    post_liked=post).delete()

                return JsonResponse({"message": "Successful"}, status=201)
            except BaseException as error:
                print("An exception occurred: {}".format(error))
    else:
        return JsonResponse({"error": "POST request required."}, status=400)
    return HttpResponseRedirect(reverse("twitter:index"))


def get_tweet(request, id):
    """Allows js to pre-fill the edit tweet function with a user's tweet so it
    can be edited."""
    id = int(id)
    data = serializers.serialize("json", Post.objects.filter(pk=id))
    return HttpResponse(data)

twitter/templates/twitter/following.html
{% extends "twitter/layout.html" %}

{% block left-sidebar %}
  <!-- BEGIN Left column -->
  <div class="col"></div>
  <!-- END Left column -->
{% endblock left-sidebar%}

{% block body %}

  <!-- BEGIN Center content column -->

  <!-- Begin Send Tweet Box/Form -->
  {% include "twitter/components/tweet-form.html" %}
  <!-- END Tweet Box -->

  <!-- BEGIN TWEET LIST-->
  {% include "twitter/components/list-tweets.html" %}
  <!-- END: TWEET LIST -->

  <!-- END: Center content column -->
{% endblock body%}

{% block right-sidebar %}
  <!-- BEGIN RIGHT SIDEBAR -->
  <div class="col"></div>
  <!-- END RIGHT SIDEBAR -->
{% endblock right-sidebar%}

twitter/templates/twitter/index.html
{% extends "twitter/layout.html" %}

{% block avatar %}
  {% include "twitter/components/user-avatar.html" %}
{% endblock avatar%}
{% block left-sidebar %}
  <!-- BEGIN Left column -->
  <div class="col"></div>
  <!-- END Left column -->
{% endblock left-sidebar%}

{% block body %}

  <!-- BEGIN Center content column -->

  <!-- Begin Send Tweet Box/Form -->
  {% include "twitter/components/tweet-form.html" %}
  <!-- END Tweet Box -->

  <!-- BEGIN TWEET LIST-->
  {% include "twitter/components/list-tweets.html" %}
  <!-- END: TWEET LIST -->

  <!-- END: Center content column -->
{% endblock body%}

{% block right-sidebar %}
  <!-- BEGIN RIGHT SIDEBAR -->
  <div class="col"></div>
  <!-- END RIGHT SIDEBAR -->
{% endblock right-sidebar%}

twitter/templates/twitter/layout.html
{% load static %}
{% load app_tags %}
<!DOCTYPE html>
<html lang="en">
  {# Template Credit: https://github.com/jvadillo/twitter-bootstrap #}

  <head>
    <link rel="icon" type="image/x-icon" href="{% static 'twitter/images/favicon.ico' %}"/>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css'>
    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/font/octicons.min.css'>
    <link href="{% static 'twitter/styles.css' %}" rel="stylesheet">
    <title>
      {% block title %}Social Network{% endblock %}
    </title>

  </head>

  <body>
    <!-- Fixed top navbar -->

    <nav class="navbar navbar-toggleable-md fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Profile background large image -->
      <div class="collapse navbar-collapse container">

        <!-- Navbar navigation links -->
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'twitter:user_profile' pk=user.id %}">
                <i class="octicon octicon-home" aria-hidden="true"></i>
                {{user.username}}
                <span class="sr-only">(current)</span></a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class=" nav-link" href="{% url 'twitter:index' %}">
              <i class="octicon octicon-zap"></i>
              All Posts</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'twitter:user_following' pk=user.id %}">
                <i class="octicon octicon-bell"></i>
                Following</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'twitter:logout' %}">
                <i class="octicon octicon-inbox"></i>
                Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'twitter:login' %}">
                <i class="octicon octicon-inbox"></i>
                Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'twitter:register' %}">
                <i class="octicon octicon-inbox"></i>
                Register</a>
            </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto" id="twitter-right-nav">
          <li class="nav-item">
            <a class=" nav-link" href="{% url 'portfolio:index' %}">
              <i class="octicon octicon-home"></i>
              Return To Portfolio</a>
          </li>
        </ul>
        <!-- END: Navbar navigation links -->
        <!-- Navbar Tweet button -->

        {% if user.is_authenticated %}
          <button class="btn btn-search-bar toggle">Write Tweet</button>
        {% endif %}
      </div>
    </nav>
    <!-- END: Fixed top navbar -->
    <div class="body">
      <div class="main-container">
        <div class="row ">
          {% if user.is_authenticated %}
            <img class="profile-background" src="{{ user.profile.background_image }}" alt="">
          {% else %}
            <img class="profile-background" src="https://images.pexels.com/photos/1435849/pexels-photo-1435849.jpeg?cs=srgb&dl=pexels-engin-akyurt-1435849.jpg&fm=jpg" alt="">
          {% endif %}
          <div class="container">
            <!-- User main avatar -->
            <div class="avatar-container">
              {% if not user.is_authenticated %}
                <div class="avatar"></div>
              {% else %}
                {% block avatar %}{% endblock avatar %}
              {% endif %}
            </div>
          </div>
        </div>
        {# BEGIN STAT BAR #}
        <nav class="navbar profile-stats">
          <div class="container">
            <div class="row">
              <div class="col"></div>
              <div class="col-6 middle-bar d-flex justify-content-center">
                {% block stats %}{% endblock stats%}
              </div>
              <div class="col"></div>
            </div>
          </div>
        </nav>
        {# END STAT BAR #}
        <div class="container main-content">
          <div class="d-flex justify-content-center">
            {% block left-sidebar %}{% endblock left-sidebar%}
            <div class="col-6 compose-form">
              {% block body %}{% endblock body%}
            </div>
            {% block right-sidebar %}{% endblock right-sidebar%}
          </div>
        </div>
      </div>
    </div>
    <script src='https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js'></script>
    <script src="{% static 'twitter/scripts.js' %}" rel="stylesheet"></script>
  </body>

</html>

twitter/templates/twitter/login.html
{% extends "twitter/layout.html" %}

{% block body %}
  <div class="mt-3 pt-3">
    <h2>Login</h2>

    {% if message %}
      <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'twitter:login' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <input autofocus="autofocus" class="form-control" type="text" name="username" placeholder="Username">
      </div>
      <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
      </div>
      <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account?
    <a href="{% url 'twitter:register' %}">Register here.</a>
  </div>
{% endblock %}

twitter/templates/twitter/profile.html
{% extends "twitter/layout.html" %}

{% block avatar %}
  {% include "twitter/components/other-users-avatar.html" %}
{% endblock avatar%}

<!-- BEGIN STATS BAR -->
{% block stats%}
  {% include "twitter/components/user-stats.html" %}
{% endblock stats%}
<!-- END STATS BAR -->

<!-- BEGIN Left column -->
{% block left-sidebar %}
  {% include "twitter/components/left-sidebar.html" %}
{% endblock left-sidebar%}
<!-- END Left column -->

{% block body %}
  <!-- BEGIN Center content column -->

  <!-- Begin Send Tweet Box/Form -->
  {% include "twitter/components/tweet-form.html" %}
  <!-- END Tweet Box -->

  <!-- BEGIN TWEET LIST-->
  {% include "twitter/components/list-tweets.html" %}
  <!-- END: TWEET LIST -->

  <!-- END: Center content column -->

{% endblock %}
<!-- BEGIN RIGHT SIDEBAR -->
{% block right-sidebar %}
  {% include "twitter/components/right-sidebar.html" %}
{% endblock right-sidebar%}
<!-- END RIGHT SIDEBAR -->

twitter/templates/twitter/register.html
{% extends "twitter/layout.html" %}

{% block body %}
  <div class="mt-3 pt-3">
    <h2>Register</h2>

    {% if message %}
      <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'twitter:register' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <input class="form-control" autofocus="autofocus" type="text" name="username" placeholder="Username" required="required">
      </div>
      <div class="form-group">
        <input class="form-control" autofocus="autofocus" type="text" name="first_name" placeholder="First Name" required="required">
      </div>
      <div class="form-group">
        <input class="form-control" autofocus="autofocus" type="text" name="background_img" placeholder="Background Image URL">
      </div>
      <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Email Address" required="required">
      </div>
      <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password" required="required">
      </div>
      <div class="form-group">
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password" required="required">
      </div>
      <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account?
    <a href="{% url 'twitter:login' %}">Log In here.</a>
  </div>
{% endblock %}