movies/urls.py
from django.urls import path, include
from movies import views

app_name = "movies"

urlpatterns = [
    path("", views.index, name="index"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("add", views.add, name="add"),
    path("select/<str:title>", views.select, name="select"),
    path("delete/<int:id>", views.delete, name="delete"),
    path("find/<int:id>", views.find, name="find"),
]

twitter/urls.py
from django.urls import path
from twitter import views

app_name = "twitter"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<int:pk>", views.user_profile, name="user_profile"),
    path("follow/<int:id>", views.follow, name="follow"),
    path("unfollow/<int:id>", views.unfollow, name="unfollow"),
    path("send-tweet/<int:pk>", views.send_tweet, name="send_tweet"),
    path("following/<int:pk>", views.user_following, name="user_following"),
    # API
    path("like", views.like, name="like"),
    path("get-tweet/<int:id>", views.get_tweet, name="get_tweet"),
    path("edit-tweet", views.edit_tweet, name="edit_tweet"),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from portfolio import urls as portfolio_urls
from movies import urls as movies_urls
from twitter import urls as twitter_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(portfolio_urls)),
    path("movies/", include(movies_urls)),
    path("twitter/", include(twitter_urls)),
]

twitter/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class User(AbstractUser):
    def __str__(self):
        return f"{self.username}"


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    background_image = models.URLField(null=True)
    date_joined = models.DateField(auto_now=False,
                                   auto_now_add=False,
                                   null=False,
                                   default=now)
    followers = models.ManyToManyField(User,
                                       blank=True,
                                       related_name="followed_by")

    def __str__(self):
        return f"{self.user.first_name}"


class Post(models.Model):
    author = models.ForeignKey(User,
                               null=True,
                               on_delete=models.CASCADE,
                               related_name="author")
    post_body = models.CharField(max_length=500000)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post_body[0:5]}"


class Like(models.Model):

    user_liked = models.ForeignKey(User,
                                   null=True,
                                   on_delete=models.CASCADE,
                                   related_name="user")
    post_liked = models.ForeignKey(
        Post,
        null=True,
        on_delete=models.CASCADE,
        related_name="post",
    )

    def __str__(self):
        return f"User {self.user_liked.username} likes {self.post_liked.post_body[0:5]}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

twitter/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.core import serializers
from twitter.util import *
from twitter.models import User, Post, Like, Profile
import json, traceback


def index(request):
    """When visiting homepage, show all tweets"""

    all_tweets = Post.objects.all()
    tweets = sort_tweets(all_tweets)
    tweets = paginate(request, tweets)
    likes = like_count()

    return render(
        request,
        "twitter/index.html",
        {
            "posts": tweets,
            "likes": likes,
        },
    )


def login_view(request):
    """Allow registered user to login"""
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("twitter:index"))
        else:
            return render(
                request,
                "twitter/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "twitter/login.html")


def logout_view(request):
    """Allow registered user to logout"""
    logout(request)
    return HttpResponseRedirect(reverse("twitter:index"))


def register(request):
    """Allow unregistered user to register"""
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        first_name = request.POST["first_name"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "twitter/register.html",
                          {"message": "Passwords must match."})

        # Attempt to create new user
        try:
            user = User.objects.create_user(username,
                                            email,
                                            password,
                                            first_name=first_name)
            user.save()
            # Save userinfo record
            user = User.objects.get(pk=user.id)
            user.profile.background_image = request.POST["background_img"]
            user.save()
        except IntegrityError:
            return render(request, "twitter/register.html",
                          {"message": "Username already taken."})
        login(request, user)
        return HttpResponseRedirect(reverse("twitter:index"))
    else:
        return render(request, "twitter/register.html")


def user_profile(request, pk):
    """Returns a user profile page for a specific user"""
    user_profile_id = User.objects.get(pk=pk)
    specific_tweets = Post.objects.filter(author__id=pk)
    tweets = sort_tweets(specific_tweets)
    tweets = paginate(request, tweets)
    num_tweets = tweet_count(pk)
    likes = like_count()
    is_following = confirm_user_follows(request, pk)

    # get a suggested follower list and limit to 10
    if request.user.is_authenticated:
        other_users = who_to_follow(request)[:10]

    # get followers/following count from util.py
    user_following_count, user_followed_by_count = follow_nums(user_profile_id)

    return render(
        request,
        "twitter/profile.html",
        {
            "likes": likes,
            "tweet_count": num_tweets,
            "is_following": is_following,
            "user_follows": user_following_count,
            "user_followed_by": user_followed_by_count,
            "user_profile_id": user_profile_id,
            "posts": tweets,
            "follow_suggestions": other_users,
        },
    )


@login_required(login_url="login")
def send_tweet(request, pk):
    """Allows an authenticated user to send a tweet"""
    if request.method == "POST":
        user = User.objects.get(pk=request.user.id)
        tweet_body = request.POST["tweet_body"]
        new_tweet = Post.objects.create(author=user, post_body=tweet_body)
        new_tweet.save()
        return user_profile(request, pk)


@login_required(login_url="login")
def edit_tweet(request):
    """Allows an authenticated user to edit their own tweet."""
    data = json.loads(request.body)
    id = data.get("id", "")
    body = data.get("post_body", "")
    edited_tweet = Post.objects.get(pk=int(id))
    edited_tweet.post_body = body
    edited_tweet.save()
    return JsonResponse({"status": 201})


@login_required(login_url="login")
def user_following(request, pk):
    """Returns a list of who the user is following and those user's tweets."""
    followed_people = Profile.objects.filter(followers__id=pk).values("user")
    tweets = Post.objects.filter(author__in=followed_people)
    tweets = sort_tweets(tweets)
    tweets = paginate(request, tweets)
    return render(
        request,
        "twitter/following.html",
        {"posts": tweets},
    )


# Functionality views that didn't belong in utilities.py


def follow(request, id):
    """Functionality to follow a user"""
    if request.method == "POST":
        to_follow = Profile.objects.get(user=id)
        to_follow.followers.add(request.user)
        to_follow.save()
        return user_profile(request, id)


def unfollow(request, id):
    """Functionality to unfollow a user"""
    if request.method == "POST":
        to_unfollow = Profile.objects.get(user=id)
        to_unfollow.followers.remove(request.user)
        to_unfollow.save()
        return user_profile(request, id)


@login_required(login_url="login")
def like(request):
    """Functionality to like a user"""
    # Get form data
    data = json.loads(request.body)
    post_id = data.get("post_liked", "")
    post = Post.objects.get(pk=int(post_id))
    user_who_likes = Like.objects.filter(user_liked=request.user.id,
                                         post_liked=post)
    if request.method == "POST":
        if not user_who_likes:
            try:
                like = Like(user_liked=request.user, post_liked=post)
                like.save()
                return JsonResponse({"message": "Successful"}, status=201)
            except BaseException as error:
                print("An exception occurred: {}".format(error))
        if user_who_likes:
            try:
                Like.objects.filter(user_liked=request.user,
                                    post_liked=post).delete()

                return JsonResponse({"message": "Successful"}, status=201)
            except BaseException as error:
                print("An exception occurred: {}".format(error))
    else:
        return JsonResponse({"error": "POST request required."}, status=400)
    return HttpResponseRedirect(reverse("twitter:index"))


def get_tweet(request, id):
    """Allows js to pre-fill the edit tweet function with a user's tweet so it
    can be edited."""
    id = int(id)
    data = serializers.serialize("json", Post.objects.filter(pk=id))
    return HttpResponse(data)

twitter/templates/twitter/components/edit-tweet.html
<div class="wrapper tweet-edit-form" data-edit="{{post.id}}">
  <form id="form-{{post.id}}">
    <div class="form-group">
      <textarea required="true" aria-label="Edit Your Tweet" id="body-{{post.id}}" data-body='{{post.id}}' class="form-control" name="tweet_body" rows="3"></textarea>
    </div>
    <div class="bottom">
      <div class="content">
        <button type="submit" class="btn btn-primary" id="submit-{{post.id}}">Submit</button>
      </div>
    </div>
  </form>
</div>

twitter/templates/twitter/components/left-sidebar.html
<div class="col profile-col">
  <div class="profile-header">
    <!-- Header information -->
    <h3 class="profile-fullname">
      <a>{{user_profile_id.first_name}}
        <a></h3>
        <h2 class="profile-element">
          <a href="{% url 'twitter:user_profile' pk=user_profile_id.id %}">
            @{{ user_profile_id.username }}
          </a>
        </h2>
        <h2 class="profile-element">
          <i class="octicon octicon-calendar"></i>Joined
          {{ user_profile_id.profile.date_joined }}</h2>
        {# Show follow button if not current logged in user #}
        {% if user != user_profile_id and is_following == False %}
          <form action="{% url 'twitter:follow' id=user_profile_id.id %}" method="post">
            {% csrf_token %}
            <button class="btn btn-primary follow-toggle">Follow</button>
          </form>
        {% elif user != user_profile_id and is_following %}
          <form action="{% url 'twitter:unfollow' id=user_profile_id.id %}" method="post">
            {% csrf_token %}
            <button class="btn btn-primary follow-toggle">Unfollow</button>
          </form>
        {% endif %}
      </div>
    </div>

twitter/templates/twitter/components/list-tweets.html
{% load app_tags %}
<ol class="tweet-list">
  {% for post in posts %}
    <li class="tweet-card">
      <div class="tweet-content">
        <div class="tweet-header">
          <span class="fullname">
            <strong>{{post.author.first_name}}</strong>
          </span>
          {% if user.is_authenticated %}
            <a href="{% url 'twitter:user_profile' pk=post.author.id %}">
              <span class="username">@{{post.author.username}}</span></a>
          {% else %}
            <span class="username">@{{post.author.username}}</span>
          {% endif %}
          <span class="tweet-time">-
            {{post.date_created}}</span>
        </div>
        <a>
          <img class="tweet-card-avatar" src="{{ post.author|gravatar:50 }}" alt="">
        </a>
        <div class="tweet-text">
          <p class="tweet-body" data-tweet="{{post.id}}" data-edited="{{post.id}}" lang="es" data-aria-label-part="0">{{post.post_body}}
          </p>
          <p>{% include "twitter/components/edit-tweet.html" %}</p>
        </div>
        <div class="tweet-footer">
          <form class="like-form">
            <a class="tweet-footer-btn">
              <label for="like-button" class="btn pr-0">
                <i id="heart-{{post.id}}" class="octicon octicon-heart liked " aria-hidden="true" data-value="{{post.id}}"></i>
              </label>
              <input type="submit" value="{{user.id}}" class="d-none"/>
              {% for key, value in likes.items %}
                {% if key == post.id %}
                  <span id="id-{{post.id}}" class="like ml-0">{{ value }}</span>
                {% endif %}
              {% endfor %}
            </a>
            {% if user.is_authenticated and user == post.author %}
              <a class="edit">
                <i class="fa fa-pencil-square-o edit-tweet-icon" aria-hidden="true" data-user="{{post.author.id}}" data-id="{{post.id}}">Edit</i>
              </a>
            {% endif %}
          </form>
        </div>
      </div>
    </li>
    {% empty %}
    <li>This user has no tweets to share at the moment.</li>
  {% endfor %}
</ol>
<!--Pagination-->
<nav aria-label=" Page navigation example">
  <ul class="pagination justify-content-center">
    {% if posts.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
      </li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="page-item active" aria-current="page">
          <span class="page-link">
            {{ i }}
            <span class="sr-only">(current)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
      </li>
    {% endif %}
  </ul>
</nav>
<!--end of Pagination-->

twitter/templates/twitter/components/other-users-avatar.html
{% load app_tags %}
<div class="avatar" style="background-image: url('{{ user_profile_id|gravatar:50 }}');"></div>

twitter/templates/twitter/components/right-sidebar.html
{% load app_tags %}
<div class="col right-col">
  <div class="content-panel">
    <div class="panel-header text-center">
      <h4>Meet New Friends</h4>
    </div>
    <!-- Meet New Friends panel -->
    <div class="panel-content">
      <!--Follow list -->
      <ol class="tweet-list">
        {% for other_users in follow_suggestions %}
          <li class="tweet-card">
            <div class="tweet-content">
              <img class="tweet-card-avatar" src="{{ other_users|gravatar:50 }}" alt="">
              <div class="tweet-header">
                <span class="profile-fullname">
                  <strong>{{other_users.first_name}}</strong>
                </span>
                <p>
                  <a href="{% url 'twitter:user_profile' pk=other_users.id %}">
                    <span class="username">@{{other_users.username}}</span></a>
                </p>

              </div>
            </div>
          </li>
        {% endfor %}
      </ol>
      <!--END: Follow list -->
    </div>
  </div>

twitter/templates/twitter/components/tweet-form.html
{% if user.is_authenticated %}
  <div class="toggleBox">
    <div class="wrapper">
      <form action="{% url 'twitter:send_tweet' pk=user.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <textarea required="true" aria-label="Send A Tweet" class="form-control" name="tweet_body" placeholder="What's happening?" rows="3"></textarea>
        </div>
        <div class="bottom">
          <div class="content">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endif %}

twitter/templates/twitter/components/user-avatar.html
{% load app_tags %}
<div class="avatar" style="background-image: url('{{ user|gravatar:50 }}');"></div>

twitter/templates/twitter/components/user-stats.html
<ul>
  <li class="profile-stats-item-active">
    <a>
      <span class="profile-stats-item profile-stats-item-label">Tweets</span>
      <span class="profile-stats-item profile-stats-item-number">{{tweet_count}}</span>
    </a>
  </li>
  <li>
    <a>
      <span class="profile-stats-item profile-stats-item-label">Following</span>
      <span class="profile-stats-item profile-stats-item-number">{{user_follows}}</span>
    </a>
  </li>
  <li>
    <a>
      <span class="profile-stats-item profile-stats-item-label">Followers</span>
      <span class="profile-stats-item profile-stats-item-number">{{user_followed_by}}</span>
    </a>
  </li>
</ul>